name = "disclaude-bridge"
main = "src/index.js"
compatibility_date = "2024-12-01"

# KV Namespace bindings
[[kv_namespaces]]
binding = "SESSIONS"
id = "your-kv-namespace-id"
preview_id = "your-preview-kv-namespace-id"

# Environment variables (set these in Cloudflare dashboard or via wrangler secret)
[vars]
ENVIRONMENT = "development"

# Secrets to be set via wrangler secret put
# DISCORD_BOT_TOKEN
# CLAUDE_AUTH_TOKEN